language: ruby
rvm:
- 2.1
script: "./scripts/cibuild"
branches:
  only:
  - gh-pages
  - master
  - "/pages-(.*)/"
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash .scripts/deploy.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/HaoZeke/CommaCentral.git
  - secure: YOXvdd3n0KnIBcBjMvdkqPxiRqNqfOHboGJQKlvQYSurDf2e5FS4NUTgUzSk9NrjbatOrVwJD1qR3fRH3Vn7Ti0QQpqOdAn1+g1PdEx+DlyL9Z52UKhEiC/+xI/E3c4vpgRsaJddbgpmwnnuIxg5IkOG4gAB+TEYwCmMpmJM5FXY4K4ahleN0qs3lRB+0e+Q8q9TYHjVWFvn7hqmVxPGmj6OCvlb64ESniVU833OoCUYQZt8zdur3zOBcq9EGgSQN3qBbXtCaJ+zDI8uucGknNlLHLGgymrq4T+Jqf7zHWx3FTNHOwTuIYdLSxeh1RFEBp4wljaE8PKXfM9Q3U52KRpCNt1OYO3Nwyxjsw3X8gGLjhjee5nug7ZLyyBalDGYeWkemYIsR7J1jtIBD1M+Q3FTawob1tKEmhineoAgcqoYs5ayH2lv8Xopybo2h3Ev9Rt0xtXt2Xl+MAcAB1KoJAIMKvxFdT5qiNjUsPbdG0DsKNSQtOM4m4QPDQ4AEu73T/h9NJDEz6sYCtVk4dUm3+zRNUUnaWnRgqGusMuy6d4x0hSY8frbTptvkQul2FlvfiL2Q3dDkRWXdiYD0WHX14jNKiPdfI+wHZyesOYPC6Px3o9LfgMB4jxhGVk/fVi6IiFx4HOdkkigCcy34EW80Ls4FnYLunP3J1iCNPSfC7k=
