# Website info
name: 'Comma Central'
title: 'Comma Central'
description: "A beautiful narrative written with the world's most elegant publishing platform. The story begins here."

# Author's info
author: 'Comma Central'
username: commacen
bio: 'Curator and bot extraordnaire'
location: 'Kanpur, India'
url: 'http://haozeke.github.io/CommaCentral/'
image: 'assets/images/commacen.png'

# Jykell configuration
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
#highlighter: pygments
paginate: 5
language: 'en-uk'
short_url: 'haozeke.github.io/CommaCentral'
google_analytics: UA-70004924-1
addthis_id: ra-5644fcb7b7776b84
disqus: commacentral
baseurl: /CommaCentral/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# Compress our CSS 
sass:
 style: :compressed

# gems and other configs
gems: 
	- jekyll-paginate
	- jekyll-minifier

exclude: ["vendor"]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
